language: php

php:
  - 7.0
  - 7.1

before_script:
  - wget https://github.com/ImageMagick/ImageMagick/archive/6.9.9-33.tar.gz
  - tar -xvzf 6.9.9-33.tar.gz
  - cd ImageMagick-6.9.9-33
  - ./configure
  - sudo make
  - sudo make install
  - cd ..
  - printf "\n" | pecl install imagick
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
