language: php

php:
  - 7.0
  - 7.1

before_script:
  # - sudo add-apt-repository -y ppa:evl.ms/precise
  - sudo apt-get update
  - sudo apt-get -y --force-yes --reinstall install imagemagick
  - printf "\n" | pecl install imagick
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
